#############
# Format
## Armour (inc. shields & cloak)
# [<slot>.<heavy/medium/light>.<rarity>]
# <stat> = [<new gear value>, <maxed value>]
## Weapon
# [<melee/bow/staff>.<type>.<rarity>]
# <stat> = [<new gear value>, <maxed value>]
#
# Tips
# If you're trying to find something, search for it!
#############

# Head
## Heavy
[head.heavy.rare]
armour = ["23?", "33?"]
magic = ["20?", "30?"]
str = ["15?", "20?"]
dex = [0]
int = [0]
vit = ["15?", "20?"]

[head.heavy.epic]
armour = ["24?", "34?"]
magic = ["21?", "31?"]
str = ["16?", "21?"]
dex = [0]
int = [0]
vit = ["16?", "21?"]

[head.heavy.legendary]
armour = ["26?", "36?"]
magic = ["21?", "31?"]
str = ["18?", "23?"]
dex = [0]
int = [0]
vit = ["17?", "22?"]

## Medium
[head.medium.rare]
armour = ["20?", "30?"]
magic = ["17?", "27?"]
str = [0]
dex = ["15?", "20?"]
int = [0]
vit = ["13?", "17?"]

[head.medium.epic]
armour = ["21?", "31?"]
magic = ["18?", "28?"]
str = [0]
dex = ["16?", "21?"]
int = [0]
vit = ["14?", "18?"]

[head.medium.legendary]
armour = ["23?", "33?"]
magic = ["21?", "31?"]
str = [0]
dex = ["18?", "23?"]
int = [0]
vit = ["15?", "20?"]

## Light
[head.light.rare]
armour = ["17?", "27?"]
magic = ["15?", "25?"]
str = [0]
dex = [0]
int = ["15?", "20?"]
vit = ["10?", "13?"]

[head.light.epic]
armour = ["18?", "28?"]
magic = ["16?", "26?"]
str = [0]
dex = [0]
int = ["16?", "21?"]
vit = ["10?", "13?"]

[head.light.legendary]
armour = ["20?", "30?"]
magic = ["18?", "28?"]
str = [0]
dex = [0]
int = ["18?", "23?"]
vit = ["11?", "14?"]

# Shoulders
## Heavy
[shoulders.heavy.rare]
armour = ["23?", "33?"]
magic = ["20?", "30?"]
str = ["15?", "20?"]
dex = [0]
int = [0]
vit = ["15?", "20?"]

[shoulders.heavy.epic]
armour = ["24?", "34?"]
magic = ["21?", "31?"]
str = ["16?", "21?"]
dex = [0]
int = [0]
vit = ["16?", "21?"]

[shoulders.heavy.legendary]
armour = ["26?", "36?"]
magic = ["24?", "34?"]
str = ["18?", "23?"]
dex = [0]
int = [0]
vit = ["17?", "22?"]

## Medium
[shoulders.medium.rare]
armour = ["20?", "30?"]
magic = ["17?", "27?"]
str = [0]
dex = ["15?", "20?"]
int = [0]
vit = ["13?", "17?"]

[shoulders.medium.epic]
armour = ["21?", "31?"]
magic = ["18?", "28?"]
str = [0]
dex = ["16?", "21?"]
int = [0]
vit = ["14?", "18?"]

[shoulders.medium.legendary]
armour = ["22?", "33?"]
magic = ["21?", "31?"]
str = [0]
dex = ["18?", "23?"]
int = [0]
vit = ["15?", "20?"]

## Light
[shoulders.light.rare]
armour = ["17?", "27?"]
magic = ["15?", "25?"]
str = [0]
dex = [0]
int = ["15?", "20?"]
vit = ["10?", "13?"]

[shoulders.light.epic]
armour = ["18?", "28?"]
magic = ["16?", "26?"]
str = [0]
dex = [0]
int = ["16?", "21?"]
vit = ["10?", "13?"]

[shoulders.light.legendary]
armour = ["20?", "30?"]
magic = ["18?", "28?"]
str = [0]
dex = [0]
int = ["18?", "23?"]
vit = ["11?", "14?"]

# Chest
## Heavy
[chest.heavy.rare]
armour = ["23?", "33?"]
magic = ["19?", "29?"]
str = ["16?", "21?"]
dex = [0]
int = [0]
vit = ["18?", "23?"]

[chest.heavy.epic]
armour = ["24?", "34?"]
magic = ["20?", "30?"]
str = ["17?", "22?"]
dex = [0]
int = [0]
vit = ["20?", "26?"]

[chest.heavy.legendary]
armour = ["26?", "36?"]
magic = ["22?", "32?"]
str = ["17?", "22?"]
dex = [0]
int = [0]
vit = ["18?", "23?"]

## Medium
[chest.medium.rare]
armour = ["20?", "30?"]
magic = ["16?", "26?"]
str = [0]
dex = ["16?", "21?"]
int = [0]
vit = ["16?", "21?"]

[chest.medium.epic]
armour = ["21?", "31?"]
magic = ["17?", "27?"]
str = [0]
dex = ["17?", "22?"]
int = [0]
vit = ["18?", "23?"]

[chest.medium.legendary]
armour = ["23?", "33?"]
magic = ["19?", "29?"]
str = [0]
dex = ["19?", "25?"]
int = [0]
vit = ["16?", "21?"]

## Light
[chest.light.rare]
armour = ["17?", "27?"]
magic = ["13?", "23?"]
str = [0]
dex = [0]
int = ["16?", "21?"]
vit = ["12?", "16?"]

[chest.light.epic]
armour = ["18?", "28?"]
magic = ["14?", "24?"]
str = [0]
dex = [0]
int = ["17?", "22?"]
vit = ["13?", "17?"]

[chest.light.legendary]
armour = ["20?", "30?"]
magic = ["16?", "26?"]
str = [0]
dex = [0]
int = ["19?", "25?"]
vit = ["15?", "20?"]

# Gloves
## Heavy
[gloves.heavy.rare]
armour = ["19?", "29?"]
magic = ["17?", "27?"]
str = ["14?", "18?"]
dex = [0]
int = [0]
vit = ["11?", "14?"]

[gloves.heavy.epic]
armour = ["20?", "30?"]
magic = ["18?", "28?"]
str = ["15?", "20?"]
dex = [0]
int = [0]
vit = ["12?", "16?"]

[gloves.heavy.legendary]
armour = ["22?", "32?"]
magic = ["20?", "30?"]
str = ["17?", "22?"]
dex = [0]
int = [0]
vit = ["16?", "21?"]

## Medium
[gloves.medium.rare]
armour = ["16?", "26?"]
magic = ["14?", "24?"]
str = [0]
dex = ["14?", "18?"]
int = [0]
vit = ["9?", "12?"]

[gloves.medium.epic]
armour = ["17?", "27?"]
magic = ["15?", "25?"]
str = [0]
dex = ["15?", "20?"]
int = [0]
vit = ["10?", "13?"]

[gloves.medium.legendary]
armour = ["19?", "29?"]
magic = ["17?", "27?"]
str = [0]
dex = ["17?", "22?"]
int = [0]
vit = ["14?", "18?"]

## Light
[gloves.light.rare]
armour = ["13?", "23?"]
magic = ["11?", "21?"]
str = [0]
dex = [0]
int = ["14?", "18?"]
vit = ["8?", "10?"]

[gloves.light.epic]
armour = ["14?", "24?"]
magic = ["12?", "22?"]
str = [0]
dex = [0]
int = ["15?", "20?"]
vit = ["8?", "10?"]

[gloves.light.legendary]
armour = ["16?", "26?"]
magic = ["14?", "24?"]
str = [0]
dex = [0]
int = ["17?", "22?"]
vit = ["9?", "12?"]

# Legs
## Heavy
[legs.heavy.rare]
armour = ["23?", "33?"]
magic = ["19?", "29?"]
str = ["16?", "21?"]
dex = [0]
int = [0]
vit = ["18?", "23?"]

[legs.heavy.epic]
armour = ["24?", "34?"]
magic = ["20?", "30?"]
str = ["17?", "22?"]
dex = [0]
int = [0]
vit = ["20?", "26?"]

[legs.heavy.legendary]
armour = ["26?", "36?"]
magic = ["22?", "32?"]
str = ["19?", "25?"]
dex = [0]
int = [0]
vit = ["18?", "23?"]

## Medium
[legs.medium.rare]
armour = ["20?", "30?"]
magic = ["16?", "26?"]
str = [0]
dex = ["16?", "21?"]
int = [0]
vit = ["16?", "21?"]

[legs.medium.epic]
armour = ["21?", "31?"]
magic = ["17?", "27?"]
str = [0]
dex = ["17?", "22?"]
int = [0]
vit = ["18?", "23?"]

[legs.medium.legendary]
armour = ["23?", "33?"]
magic = ["19?", "29?"]
str = [0]
dex = ["19?", "25?"]
int = [0]
vit = ["16?", "21?"]

## Light
[legs.light.rare]
armour = ["17?", "27?"]
magic = ["13?", "23?"]
str = [0]
dex = [0]
int = ["16?", "21?"]
vit = ["12?", "16?"]

[legs.light.epic]
armour = ["18?", "28?"]
magic = ["14?", "24?"]
str = [0]
dex = [0]
int = ["17?", "22?"]
vit = ["13?", "17?"]

[legs.light.legendary]
armour = ["20?", "30?"]
magic = ["16?", "26?"]
str = [0]
dex = [0]
int = ["19?", "25?"]
vit = ["15?", "20?"]

# Shoes
## Heavy
[shoes.heavy.rare]
armour = ["19?", "29?"]
magic = ["17?", "27?"]
str = ["14?", "18?"]
dex = [0]
int = [0]
vit = ["11?", "14?"]

[shoes.heavy.epic]
armour = ["20?", "30?"]
magic = ["18?", "28?"]
str = ["15?", "20?"]
dex = [0]
int = [0]
vit = ["12?", "16?"]

[shoes.heavy.legendary]
armour = ["22?", "32?"]
magic = ["20?", "30?"]
str = ["17?", "22?"]
dex = [0]
int = [0]
vit = ["16?", "21?"]

## Medium
[shoes.medium.rare]
armour = ["16?", "26?"]
magic = ["14?", "24?"]
str = [0]
dex = ["14?", "18?"]
int = [0]
vit = ["9?", "12?"]

[shoes.medium.epic]
armour = ["17?", "27?"]
magic = ["15?", "25?"]
str = [0]
dex = ["15?", "20?"]
int = [0]
vit = ["10?", "13?"]

[shoes.medium.legendary]
armour = ["19?", "29?"]
magic = ["17?", "27?"]
str = [0]
dex = ["17?", "22?"]
int = [0]
vit = ["14?", "18?"]

## Light
[shoes.light.rare]
armour = ["13?", "23?"]
magic = ["11?", "21?"]
str = [0]
dex = [0]
int = ["14?", "18?"]
vit = ["8?", "10?"]

[shoes.light.epic]
armour = ["14?", "24?"]
magic = ["12?", "22?"]
str = [0]
dex = [0]
int = ["15?", "20?"]
vit = ["8?", "10?"]

[shoes.light.legendary]
armour = ["16?", "26?"]
magic = ["14?", "24?"]
str = [0]
dex = [0]
int = ["17?", "22?"]
vit = ["9?", "12?"]

# Cloak
[cloak.rare]
armour = ["17?", "27?"]
magic = ["13?", "23?"]
str = ["14?", "18?"]
dex = ["14?", "18?"]
int = ["14?", "18?"]
vit = ["14?", "18?"]

[cloak.epic]
armour = ["18?", "28?"]
magic = ["14?", "24?"]
str = ["15?", "20?"]
dex = ["15?", "20?"]
int = ["15?", "20?"]
vit = ["15?", "20?"]

[cloak.legendary]
armour = ["20?", "30?"]
magic = ["16?", "26?"]
str = ["17?", "22?"]
dex = ["17?", "22?"]
int = ["17?", "22?"]
vit = ["17?", "22?"]

# Hand
## Shield
[shield.rare]
armour = ["19?", "29?"]
magic = ["17?", "27?"]
str = [0]
dex = [0]
int = [0]
vit = ["13?", "17?"]

[shield.epic]
armour = ["20?", "30?"]
magic = ["18?", "28?"]
str = [0]
dex = [0]
int = [0]
vit = ["14?", "18?"]

[shield.legendary]
armour = ["22?", "32?"]
magic = ["22?", "32?"]
str = [0]
dex = [0]
int = [0]
vit = ["16?", "21?"]

## Melee
### Sword
[melee.sword.rare]
damage = [["20?", "22?"], ["???", "???"]]
speed = ["2.68?"]
primary = ["17?", "???"]
secondary = ["???", "???"]
normal = ["15?", "???"]

[melee.sword.epic]
damage = [["21?", "23?"], ["???", "???"]]
speed = ["2.76?"]
primary = ["18?", "???"]
secondary = ["???", "???"]
normal = ["16?", "???"]

[melee.sword.legendary]
damage = [["22?", "24?"], ["???", "???"]]
speed = ["2.40?"]
primary = ["19?", "???"]
secondary = ["???", "???"]
normal = ["17?", "???"]

### Axe
[melee.axe.rare]
damage = [["22?", "24?"], ["???", "???"]]
speed = ["2.61?"]
primary = ["17?", "???"]
secondary = ["???", "???"]
normal = ["15?", "???"]

[melee.axe.epic]
damage = [["23?", "25?"], ["???", "???"]]
speed = ["2.81?"]
primary = ["18?", "???"]
secondary = ["???", "???"]
normal = ["16?", "???"]

[melee.axe.legendary]
damage = [["24?", "26?"], ["???", "???"]]
speed = ["2.82?"]
primary = ["19?", "???"]
secondary = ["???", "???"]
normal = ["17?", "???"]

### Greatsword
#GreatSword,Rare,30-27;30-27,3.4339008;3.4339008,25;25,21;21,21;21,21;21
#GreatSword,Epic,31-28;31-28,3.3391507;3.3391507,26;26,22;22,22;22,22;22
#GreatSword,Legendary,33-30;33-30,3.1899238;3.1899238,27;27,23;23,23;23,23;23
[melee.greatsword.rare]
damage = [["27?", "30?"], ["???", "???"]]
speed = ["3.43?"]
primary = ["25?", "???"]
secondary = ["???", "???"]
normal = ["21?", "???"]

[melee.greatsword.epic]
damage = [["28?", "31?"], ["???", "???"]]
speed = ["3.34?"]
primary = ["26?", "???"]
secondary = ["???", "???"]
normal = ["22?", "???"]

[melee.greatsword.legendary]
damage = [["30?", "33?"], ["???", "???"]]
speed = ["3.19?"]
primary = ["27?", "???"]
secondary = ["???", "???"]
normal = ["23?", "???"]

### GreatAxe
#GreatAxe,Rare,33-30;33-30,3.587214;3.587214,25;25,21;21,21;21,21;21
#GreatAxe,Epic,34-31;34-31,3.3497627;3.3497627,26;26,22;22,22;22,22;22
#GreatAxe,Legendary,36-33;36-33,3.7381244;3.7381244,27;27,23;23,23;23,23;23
[melee.greataxe.rare]
damage = [["?", "?"], ["???", "???"]]
speed = ["?"]
primary = ["?", "???"]
secondary = ["???", "???"]
normal = ["?", "???"]

[melee.greataxe.epic]
damage = [["?", "?"], ["???", "???"]]
speed = ["?"]
primary = ["?", "???"]
secondary = ["???", "???"]
normal = ["?", "???"]

[melee.greataxe.legendary]
damage = [["?", "?"], ["???", "???"]]
speed = ["?"]
primary = ["?", "???"]
secondary = ["???", "???"]
normal = ["?", "???"]

## Bow
#Bow,Rare,33-30;33-30,3.3597527;3.3597527,25;25,21;21,21;21,21;21
#Bow,Epic,34-31;34-31,3.4248214;3.4248214,26;26,22;22,22;22,22;22
#Bow,Legendary,36-33;36-33,3.1462526;3.1462526,27;27,23;23,23;23,23;23
[bow.bow.rare]
damage = [["?", "?"], ["???", "???"]]
speed = ["?"]
primary = ["?", "???"]
secondary = ["???", "???"]
normal = ["?", "???"]

[bow.bow.epic]
damage = [["?", "?"], ["???", "???"]]
speed = ["?"]
primary = ["?", "???"]
secondary = ["???", "???"]
normal = ["?", "???"]

[bow.bow.legendary]
damage = [["?", "?"], ["???", "???"]]
speed = ["?"]
primary = ["?", "???"]
secondary = ["???", "???"]
normal = ["?", "???"]

## Staff
#Staff,Rare,30-27;30-27,3.0650249;3.0650249,25;25,21;21,21;21,21;21
#Staff,Epic,31-28;31-28,3.332724;3.332724,26;26,22;22,22;22,22;22
#Staff,Legendary,33-30;33-30,3.461685;3.461685,27;27,23;23,23;23,23;23
[staff.staff.rare]
damage = [["?", "?"], ["???", "???"]]
speed = ["?"]
primary = ["?", "???"]
secondary = ["???", "???"]
normal = ["?", "???"]

[staff.staff.epic]
damage = [["?", "?"], ["???", "???"]]
speed = ["?"]
primary = ["?", "???"]
secondary = ["???", "???"]
normal = ["?", "???"]

[staff.staff.legendary]
damage = [["?", "?"], ["???", "???"]]
speed = ["?"]
primary = ["?", "???"]
secondary = ["???", "???"]
normal = ["?", "???"]

