#############
# Format
## Armour (inc. shields & cloak)
# [<slot>.<heavy/medium/light>.<rarity>]
# <stat> = [<new gear value>, <maxed value>]
## Weapon
# [<melee/bow/staff>.<type>.<rarity>]
# <stat> = [<new gear value>, <maxed value>]
#
# Tips
# If you're trying to find something, search for it!
#############

# Head
## Heavy
[head.heavy.rare]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = [0]
int = [0]
vit = ["???", "???"]

[head.heavy.epic]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = [0]
int = [0]
vit = ["???", "???"]

[head.heavy.legendary]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = ["???", "???"]
int = ["???", "???"]
vit = ["???", "???"]

## Medium
[head.medium.rare]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = ["???", "???"]
int = [0]
vit = ["???", "???"]

[head.medium.epic]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = ["???", "???"]
int = [0]
vit = ["???", "???"]

[head.medium.legendary]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = ["???", "???"]
int = ["???", "???"]
vit = ["???", "???"]

## Light
[head.light.rare]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = [0]
int = ["???", "???"]
vit = ["???", "???"]

[head.light.epic]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = [0]
int = ["???", "???"]
vit = ["???", "???"]

[head.light.legendary]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = ["???", "???"]
int = ["???", "???"]
vit = ["???", "???"]

# Shoulders
## Heavy
[shoulders.heavy.rare]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = [0]
int = [0]
vit = ["???", "???"]

[shoulders.heavy.epic]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = [0]
int = [0]
vit = ["???", "???"]

[shoulders.heavy.legendary]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = [0]
int = [0]
vit = ["???", "???"]

## Medium
[shoulders.medium.rare]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = ["???", "???"]
int = [0]
vit = ["???", "???"]

[shoulders.medium.epic]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = ["???", "???"]
int = [0]
vit = ["???", "???"]

[shoulders.medium.legendary]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = ["???", "???"]
int = ["???", "???"]
vit = ["???", "???"]

## Light
[shoulders.light.rare]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = [0]
int = ["???", "???"]
vit = ["???", "???"]

[shoulders.light.epic]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = [0]
int = ["???", "???"]
vit = ["???", "???"]

[shoulders.light.legendary]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = [0]
int = ["???", "???"]
vit = ["???", "???"]

# Chest
## Heavy
[chest.heavy.rare]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = [0]
int = [0]
vit = ["???", "???"]

[chest.heavy.epic]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = [0]
int = [0]
vit = ["???", "???"]

[chest.heavy.legendary]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = ["???", "???"]
int = ["???", "???"]
vit = ["???", "???"]

## Medium
[chest.medium.rare]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = ["???", "???"]
int = [0]
vit = ["???", "???"]

[chest.medium.epic]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = ["???", "???"]
int = [0]
vit = ["???", "???"]

[chest.medium.legendary]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = ["???", "???"]
int = ["???", "???"]
vit = ["???", "???"]

## Light
[chest.light.rare]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = [0]
int = ["???", "???"]
vit = ["???", "???"]

[chest.light.epic]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = ["???", "???"]
int = ["???", "???"]
vit = ["???", "???"]

[chest.light.legendary]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = ["???", "???"]
int = ["???", "???"]
vit = ["???", "???"]

# Gloves
## Heavy
[gloves.heavy.rare]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = [0]
int = [0]
vit = ["???", "???"]

[gloves.heavy.epic]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = [0]
int = [0]
vit = ["???", "???"]

[gloves.heavy.legendary]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = ["???", "???"]
int = ["???", "???"]
vit = ["???", "???"]

## Medium
[gloves.medium.rare]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = ["???", "???"]
int = [0]
vit = ["???", "???"]

[gloves.medium.epic]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = ["???", "???"]
int = [0]
vit = ["???", "???"]

[gloves.medium.legendary]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = ["???", "???"]
int = ["???", "???"]
vit = ["???", "???"]

## Light
[gloves.light.rare]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = [0]
int = ["???", "???"]
vit = ["???", "???"]

[gloves.light.epic]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = ["???", "???"]
int = ["???", "???"]
vit = ["???", "???"]

[gloves.light.legendary]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = ["???", "???"]
int = ["???", "???"]
vit = ["???", "???"]

# Legs
## Heavy
[legs.heavy.rare]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = [0]
int = [0]
vit = ["???", "???"]

[legs.heavy.epic]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = [0]
int = [0]
vit = ["???", "???"]

[legs.heavy.legendary]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = ["???", "???"]
int = ["???", "???"]
vit = ["???", "???"]

## Medium
[legs.medium.rare]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = ["???", "???"]
int = [0]
vit = ["???", "???"]

[legs.medium.epic]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = ["???", "???"]
int = ["???", "???"]
vit = ["???", "???"]

[legs.medium.legendary]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = ["???", "???"]
int = ["???", "???"]
vit = ["???", "???"]

## Light
[legs.light.rare]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = [0]
int = ["???", "???"]
vit = ["???", "???"]

[legs.light.epic]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = [0]
int = ["???", "???"]
vit = ["???", "???"]

[legs.light.legendary]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = [0]
int = ["???", "???"]
vit = ["???", "???"]

# Shoes
## Heavy
[shoes.heavy.rare]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = [0]
int = [0]
vit = ["???", "???"]

[shoes.heavy.epic]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = [0]
int = [0]
vit = ["???", "???"]

[shoes.heavy.legendary]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = ["???", "???"]
int = ["???", "???"]
vit = ["???", "???"]

## Medium
[shoes.medium.rare]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = ["???", "???"]
int = [0]
vit = ["???", "???"]

[shoes.medium.epic]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = ["???", "???"]
int = [0]
vit = ["???", "???"]

[shoes.medium.legendary]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = ["???", "???"]
int = ["???", "???"]
vit = ["???", "???"]

## Light
[shoes.light.rare]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = [0]
int = ["???", "???"]
vit = ["???", "???"]

[shoes.light.epic]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = [0]
int = ["???", "???"]
vit = ["???", "???"]

[shoes.light.legendary]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = ["???", "???"]
int = ["???", "???"]
vit = ["???", "???"]

# Cloak
[cloak.rare]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = ["???", "???"]
int = ["???", "???"]
vit = ["???", "???"]

[cloak.epic]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = ["???", "???"]
int = ["???", "???"]
vit = ["???", "???"]

[cloak.legendary]
armour = ["???", "???"]
magic = ["???", "???"]
str = ["???", "???"]
dex = ["???", "???"]
int = ["???", "???"]
vit = ["???", "???"]

# Hand
## Shield
[shield.rare]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = [0]
int = [0]
vit = ["???", "???"]

[shield.epic]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = [0]
int = [0]
vit = ["???", "???"]

[shield.legendary]
armour = ["???", "???"]
magic = ["???", "???"]
str = [0]
dex = [0]
int = [0]
vit = ["???", "???"]

## Melee
### Sword
[melee.sword.rare]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[melee.sword.epic]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[melee.sword.legendary]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

### Axe
[melee.axe.rare]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[melee.axe.epic]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[melee.axe.legendary]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

### Greatsword
[melee.greatsword.rare]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[melee.greatsword.epic]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[melee.greatsword.legendary]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

### GreatAxe
[melee.greataxe.rare]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[melee.greataxe.epic]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[melee.greataxe.legendary]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

## Bow
[bow.bow.rare]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[bow.bow.epic]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[bow.bow.legendary]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

## Staff
[staff.staff.rare]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[staff.staff.epic]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[staff.staff.legendary]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

